### ISSUE TITLE
Grunt.js build?

### ISSUE THREAD

**Issue by dertseha** [janantala/qrcode.js#1]
Would you be interested in a Grunt.js based build?
I'd be happy to supply one, including jshint, jsbeautifier and browserify.
These things make contribution easier and the browserify step would wrap the whole library to avoid using global namespace.

**Comment by janantala** [comment]
Hi, yes I am interested. Just make a PR.
I also plan to release it as a bower package / npm.

**Comment by dertseha** [comment]
PR is live.
Adding tests would be a great addition. Though, I could provide only a framework (Mocha, expect.js - including code coverage) - because I have no idea about the internals of QR :)

Also, a travis integration could be another addition.

**Comment by janantala** [comment]
Thanks.

I will add tests and travis integration.

**Comment by dertseha** [comment]
ok - thanks for accepting.
But I'd have the other stuff ready as well :)

**Comment by janantala** [comment]
So just make another PR :)
