### ISSUE TITLE
Mismatch last release with comment

### ISSUE THREAD

**Issue by davidfou** [janantala/qrcode.js#10]
Hi!

I think you did a mistake when you did your last release. You named it 1.0.2 in your comment put you pushed 0.1.2 tag.

**Comment by janantala** [comment]
Oh, my bad. Fixed, thanks.

**Comment by sydscape** [comment]
Jan,

I am connecting with you on linked in right now as I wanted to check with you on availability to work on two projects?

Let me know if you can chat later.  I will leave my cell on the linkedin message.

**Comment by janantala** [comment]
@sydscape could you send me an email?
